import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'p1_name',
    description: 'p1_desc',
    price: 1299.99,
    image: 'product-1',
    category: 'Cameras',
    rating: 4.8,
    reviews: 152,
    specifications: {
      'Sensor': 'Full-Frame CMOS',
      'Megapixels': '45 MP',
      'Video': '4K UHD at 60fps',
      'ISO': '100-51200',
    },
    availability: 'In Stock',
  },
  {
    id: '2',
    name: 'p2_name',
    description: 'p2_desc',
    price: 349.99,
    image: 'product-2',
    category: 'Audio',
    rating: 4.6,
    reviews: 230,
    specifications: {
      'Connectivity': 'Bluetooth 5.2',
      'Battery Life': '40 Hours',
      'Driver Size': '40mm',
      'Noise Cancelling': 'Active Noise Cancellation',
    },
    availability: 'In Stock',
  },
  {
    id: '3',
    name: 'p3_name',
    description: 'p3_desc',
    price: 249.99,
    image: 'product-3',
    category: 'Wearables',
    rating: 4.5,
    reviews: 310,
    specifications: {
      'Display': '1.4" AMOLED',
      'Water Resistance': '5 ATM',
      'Sensors': 'Heart Rate, SpO2, GPS',
      'Compatibility': 'iOS & Android',
    },
    availability: 'In Stock',
  },
  {
    id: '4',
    name: 'p4_name',
    description: 'p4_desc',
    price: 1499.00,
    image: 'product-4',
    category: 'Computers',
    rating: 4.7,
    reviews: 98,
    specifications: {
      'Processor': '12th Gen Core i7',
      'RAM': '16GB DDR5',
      'Storage': '1TB NVMe SSD',
      'Display': '14" 2.8K OLED',
    },
    availability: 'In Stock',
  },
  {
    id: '5',
    name: 'p5_name',
    description: 'p5_desc',
    price: 129.99,
    image: 'product-5',
    category: 'Audio',
    rating: 4.4,
    reviews: 189,
    specifications: {
      'Connectivity': 'Bluetooth 5.0',
      'Battery Life': '20 Hours',
      'Power': '30W',
      'Waterproof': 'IPX7',
    },
    availability: 'Out of Stock',
  },
  {
    id: '6',
    name: 'p6_name',
    description: 'p6_desc',
    price: 799.00,
    image: 'product-6',
    category: 'Cameras',
    rating: 4.9,
    reviews: 75,
    specifications: {
      'Flight Time': '30 minutes',
      'Range': '5 km',
      'Camera': '4K HDR',
      'Gimbal': '3-axis stabilization',
    },
    availability: 'In Stock',
  },
  {
    id: '7',
    name: 'p7_name',
    description: 'p7_desc',
    price: 399.00,
    image: 'product-7',
    category: 'Gaming',
    rating: 4.5,
    reviews: 112,
    specifications: {
      'Resolution': '2160 x 2160 per eye',
      'Field of View': '110 degrees',
      'Refresh Rate': '90Hz',
      'Tracking': '6DoF Inside-Out',
    },
    availability: 'In Stock',
  },
  {
    id: '8',
    name: 'p8_name',
    description: 'p8_desc',
    price: 99.99,
    image: 'product-8',
    category: 'Computers',
    rating: 4.7,
    reviews: 255,
    specifications: {
      'DPI': '8000',
      'Connectivity': 'Bluetooth & 2.4GHz Wireless',
      'Buttons': '7 programmable',
      'Battery': 'Rechargeable (70 days)',
    },
    availability: 'In Stock',
  },
];

export const categories = [...new Set(products.map((p) => p.category))];
